services:
  rabbitmq:
    image: rabbitmq:4.1-management
    container_name: openstack-rabbitmq
    hostname: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/rabbitmq_definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro

  postgres:
    image: postgres:16
    container_name: openstack-postgres
    hostname: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - /var/lib/openstack-postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 20

  memcached:
    image: memcached:1.6
    container_name: openstack-memcached
    hostname: memcached
    restart: unless-stopped
    command: memcached -m 64
    ports:
      - "11211:11211"
    healthcheck:
      test: ["CMD-SHELL", "echo stats | nc localhost 11211 | grep -q uptime"]
#      test: ["CMD", "bash", "-c", "echo stats | nc localhost 11211 | grep -q uptime"]
#      test: ["CMD", "bash", "-c", "nc -zv localhost 11211"]
      interval: 5s
      timeout: 3s
      retries: 20

  keystone:
    build:
      context: .
      dockerfile: keystone-dockerfile
    container_name: openstack-keystone
    hostname: keystone
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./env.list
    depends_on:
      postgres:
        condition: service_healthy
#      memcached:
#        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/v3 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  keystone-init:
    build:
      context: .
      dockerfile: keystone-init-dockerfile
    container_name: keystone-init
    hostname: keystone-init
    env_file:
      - ./env.list
    depends_on:
      keystone:
        condition: service_healthy
    restart: "no"

  glance:
    build:
      context: .
      dockerfile: glance-dockerfile
    container_name: openstack-glance
    hostname: glance
    restart: unless-stopped
    ports:
      - "9292:9292"
    env_file:
      - ./env.list
    depends_on:
      postgres:
        condition: service_healthy
      keystone:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9292/ | grep -q CURRENT"]
      interval: 5s
      timeout: 3s
      retries: 20
