[DEFAULT]
metadata_proxy_shared_secret = metadata_secret1
# L'IP ou le nom du conteneur nova-api (metadata)
nova_metadata_host = nova-api
nova_metadata_port = 8775

[cache]
backend = dogpile.cache.memcached
enabled = True
# Utilisez le nom du service défini dans votre docker-compose
memcache_servers = memcached:11211

