[DEFAULT]
host = nova-compute
core_plugin = ml2
service_plugins = router
transport_url = rabbit://openstack:rabbit1@rabbitmq:5672/openstack
auth_strategy = keystone
notify_nova_on_port_status_changes = true
notify_nova_on_port_data_changes = true

[database]
connection = postgresql+psycopg2://neutron:neutrondb1@postgres/neutron

[keystone_authtoken]
www_authenticate_uri = http://keystone:5000
auth_url = http://keystone:5000
memcached_servers = memcached:11211
auth_type = password
project_domain_name = Default
user_domain_name = Default
project_name = service
username = neutron
password = neutron1

[nova]
auth_url = http://keystone:5000
auth_type = password
project_domain_name = Default
user_domain_name = Default
region_name = RegionOne
project_name = service
username = nova
password = nova1

[oslo_concurrency]
lock_path = /var/lib/neutron/tmp

[experimental]
linuxbridge = true