[api_database]
connection = postgresql+psycopg2://nova:novadb1@postgres/nova_api

[database]
connection = postgresql+psycopg2://nova:novadb1@postgres/nova

[DEFAULT]
transport_url = rabbit://openstack:rabbit1@rabbitmq:5672/openstack
my_ip = 192.168.86.232
enabled_apis = osapi_compute,metadata
use_neutron = true
firewall_driver = nova.virt.firewall.NoopFirewallDriver

[keystone_authtoken]
www_authenticate_uri = http://keystone:5000/
auth_url = http://keystone:5000/
memcached_servers = memcached:11211
auth_type = password
project_domain_name = Default
user_domain_name = Default
project_name = service
username = nova
password = nova1

[service_user]
send_service_user_token = true
auth_url = https://keystone/identity
auth_strategy = keystone
auth_type = password
project_domain_name = Default
project_name = service
user_domain_name = Default
username = nova
password = nova1

[glance]
api_servers = http://glance:9292

[oslo_concurrency]
lock_path = /var/lib/nova/tmp

[placement]
region_name = RegionOne
project_domain_name = Default
project_name = service
auth_type = password
user_domain_name = Default
auth_url = http://keystone:5000/v3
username = placement
password = placement1

