[api_database]
connection = postgresql+psycopg2://nova:novadb1@postgres/nova_api

[database]
connection = postgresql+psycopg2://nova:novadb1@postgres/nova

[DEFAULT]
transport_url = rabbit://openstack:rabbit1@rabbitmq:5672/openstack

[keystone_authtoken]
auth_url = http://keystone:5000
memcached_servers = memcached:11211
project_name = service
username = nova
password = nova1

[placement]
auth_url = http://keystone:5000
username = placement
password = placement1
project_name = service

[DEFAULT]
my_ip = 192.168.86.232
enabled_apis = osapi_compute,metadata
use_neutron = true
firewall_driver = nova.virt.firewall.NoopFirewallDriver


